import type { Provider } from './providers/types.js';
import {
  anthropic,
  deepseek,
  gemini,
  groq,
  huggingface,
  koboldcpp,
  llamacpp,
  lmstudio,
  mistral,
  mockProvider,
  moonshot,
  ollama,
  openai,
  openrouter,
  vercelAiGateway,
  together,
  vllm,
  xai,
  zai,
} from './providers/index.js';

/** The providers that ship with ModelHitch out of the box. */
export const defaultProviders: Provider[] = [
  vercelAiGateway,
  openai,
  anthropic,
  groq,
  openrouter,
  together,
  huggingface,
  gemini,
  deepseek,
  xai,
  mistral,
  moonshot,
  zai,
  lmstudio,
  ollama,
  vllm,
  llamacpp,
  koboldcpp,
  mockProvider,
];
